controller_manager_ns: /
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - S_joint_x
      - S_joint_y
      - E_joint
      - W_joint
